version: '3.8'

services:

  database:
    image: postgres:13
    container_name: server_db
    restart: always
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    depends_on:
      - database
    container_name: server_app
    build: ./server
    ports:
      - '3000:3000'
    environment:
      DB_HOST: database
      DB_USER: ${TYPEORM_USERNAME}
      DB_PASSWORD: ${TYPEORM_PASSWORD}
      DB_NAME: ${TYPEORM_DATABASE}
      DB_PORT: ${TYPEORM_PORT}
    volumes:
      - type: bind
        source: ./server/src/migration
        target: /src/migration
        read_only: false
